### ISSUE TITLE
What are the devices?

### ISSUE THREAD

**Issue by hsrmt** [viktorvano/Remote-Robot#1]
I was wondering what are the names of the devices on the top and the bottom of this image?

![Untitled](https://user-images.githubusercontent.com/63776302/167256463-e90e5cad-5681-4d6d-9e77-26882c7089b7.png)

**Comment by viktorvano** [comment]
One of them is an LED panel, and the second one is a 3.3V step-down module. I will share links below:

€ 0,56  5%OFF | 1PCS high quality 5730 smd 5V 430mA~470mA White Mirco Usb 5730 LED lighting panel USB mobile light Emergency light night light
https://a.aliexpress.com/_mtjhhkm


€ 0,86  2%OFF | DC USB Step Down Module 9V 12V 19V To 5V 3.3V 3A Power Supply Charger Module Voltage Regulator For Vehicle Car Phone Pad
https://a.aliexpress.com/_mqZIZLG

**Comment by hsrmt** [comment]
Thank you so much! I appreciate it.
